// ===================== SPRITE DATA =====================
// Creatures are 24x24. Symmetric ones are authored as 12-wide left halves
// and mirrored; asymmetric ones are authored full-width.
// Names MUST match enemy.name strings in data.js exactly.
//
// defSprite(name, rows, opts)
//   opts.sym  : true (default) -> rows are left halves (<=12 chars), mirrored to 24
//               false -> rows are full width (<=W chars)
//   opts.w    : full width for asymmetric sprites (default 24)
//   opts.pal  : per-sprite palette overrides

const SPRITES = {};

function _pad(row, n) {
  row = row || "";
  if (row.length > n) return row.slice(0, n);
  return row + ".".repeat(n - row.length);
}

function defSprite(name, rows, opts) {
  opts = opts || {};
  const sym = opts.sym !== false;
  let pixels;
  if (sym) {
    const half = rows.map(r => _pad(r, 12));
    pixels = mirrorRows(half);
  } else {
    const w = opts.w || 24;
    pixels = rows.map(r => _pad(r, w));
  }
  SPRITES[name] = { w: pixels[0].length, h: pixels.length, pixels, palette: opts.pal || null };
}

// ---- Loup-Garou (werewolf, brown, red eyes) ----
defSprite("Loup-Garou", [
  "",
  "...kk",
  "..knnk",
  "..knnnk",
  ".knnnnnk",
  ".knnnnnnnk",
  ".knnnnnnnnnn",
  "knRRnnnnnnnN",
  "knRRnnnnnnnN",
  "kNnnnnnnnnNN",
  ".kNnnnnnNN",
  "..kNnnnNk",
  "...knWWWNk",
  "....kWWk",
  ".nnNnnnnnnnn",
  "nnNnnnnnnnnn",
  "nNnnnnttnnnn",
  "knnnnnttnnnn",
  "WkNnnnnttnnn",
  "WWkNnnnnnnnn",
  ".WkNnnnnnnnN",
  "..nnnnnNn",
  "..knnnk",
  "...kWWk",
]);

// ---- Bête du Gévaudan (great maned beast, reddish, yellow eyes) ----
defSprite("Bête du Gévaudan", [
  "",
  ".....k",
  "....knnk",
  "...konnok",
  "..konnnook",
  ".konooonnok",
  ".kooonyynoo",
  "kooonyynooon",
  "koonnnnnooon",
  "koooonnnoooN",
  ".kooWnnWook",
  "..kWWnnWWk",
  "...kWWWWk",
  "..oooooooooo",
  ".oooonnnoooo",
  "ooonnttttnoo",
  "oonntttttnoo",
  "konntttttnok",
  "WkoonttttooN",
  "WWkooonnoooo",
  ".WkoooonnnoN",
  "..oonnNNnoo",
  "..konnk",
  "...kWWk",
]);

// ---- Korrigan (little Breton sprite, red cap, green skin, big eyes) ----
defSprite("Korrigan", [
  "",
  "",
  "....rr",
  "...rrrr",
  "..rrrrrr",
  ".rrrrrrrr",
  "rrrrrrrrrr",
  ".kkeeeeeek",
  ".keWWeeWWe",
  ".keWkeeWke",
  ".keeeeeeee",
  ".keeenneee",
  ".keeemmeee",
  "..keeeeee",
  "..nneeeenn",
  ".nnneeeennn",
  "nnnWeeeeWnn",
  "nneeeeeeenn",
  ".neeeeeeee",
  ".keeeeeeek",
  "..keeeeeek",
  "..knk..knk",
  "..kWk..kWk",
  "",
]);

// ---- Maître Renard (cunning fox, orange) ----
defSprite("Maître Renard", [
  "",
  "...k....k",
  "..kok..ko",
  "..kook.koo",
  "..koookooo",
  ".kooooooo",
  ".kooyyoooo",
  "kooyyoyyooo",
  "koooooooooo",
  "kooWnnnWooN",
  ".koWWnWWook",
  "..kWWWWWk",
  "...kWWWk",
  "..oooooooo",
  ".ooooWWoooo",
  "oooooWWooooo",
  "ookooWWookoo",
  "WkoooWWoooo",
  "Wkooooooooo",
  ".kooooooonn",
  "..oooonnNNn",
  "..konnWWNN",
  "...koooNN",
  "....kWWk",
]);

// ---- Cauchemar (nightmare mare, spectral black horse, red eyes) ----
defSprite("Cauchemar", [
  "",
  "....hh",
  "...hhhh",
  "..hhKKhh",
  "..hKKKKh",
  ".hKKKKKK",
  ".hKKRRKKK",
  ".hKKKKKKK",
  "hKKKKKKKKh",
  "hKKKKKKKKh",
  "hhKKKKKKhh",
  ".hKKKKKKh",
  ".phhKKhhp",
  "phhhKKKhhp",
  "hpphKKhpph",
  ".phKKKKhp",
  "..hKKKKh",
  "..hKKKKh",
  ".phKKKKhp",
  ".hhKKKKhh",
  "..hhKKhh",
  "...hhhh",
  "..pp..pp",
  ".p......p",
]);

// ---- Bête du Mercantour (shadow wolf, grey, green eyes) ----
defSprite("Bête du Mercantour", [
  "",
  "...kk",
  "..kggk",
  "..kgggk",
  ".kgggggk",
  ".kgggUUgk",
  ".kgEEgggUg",
  "kgEEggggUUg",
  "kgggggggUUg",
  "kgUggggggUG",
  ".kgUWgWUgk",
  "..kgWWWgk",
  "...kWWWk",
  ".gggUgggggg",
  "ggUgggggUUgg",
  "gUgggggggUUg",
  "kgggggUUgggk",
  "WkgUgggggUgg",
  "WWkgggggggUg",
  ".WkgUgggggUG",
  "..gggUUgggg",
  "..kggk.kggk",
  "...kWk..kWk",
  "",
]);

// ---- Tarasque (dragon-turtle, spiked green shell) ----
defSprite("Tarasque", [
  "",
  "",
  "........kqk",
  ".......kqqqk",
  "......kqyyq",
  ".....kqqqqq",
  "....kqWWWqq",
  "...qqqqqqq",
  "..eqeqeqeqe",
  ".eqEqEqEqEqE",
  "eEqEEEEEEqEE",
  "qEEqEEEEqEEE",
  "EEEEqEEEqEEE",
  "qEEEEEEEqEEE",
  "EqEqEqEqEqEq",
  "qEEEEEEEEEEE",
  ".eqEqEqEqEqE",
  "..EEEEEEEEEE",
  ".nEEEEEEEEEn",
  "nnEqEEEEqEnn",
  "nNnEEEEEEnNn",
  "knkEEEEEEknk",
  "kWk......kWk",
  "",
]);

// ---- Ankou (hooded reaper of death, scythe — asymmetric, full width) ----
defSprite("Ankou", [
  "..........u.............",
  "..........u.............",
  "....kkkk..u.............",
  "...kxxxxk.u.............",
  "..kxKKKKxku.............",
  "..kxWWWWxku.............",
  "..kxWkkWxkuu............",
  "..kxWWWWxk.uuu..........",
  "..kxKWWKxk...uuuu.......",
  "...kxxxxk......uuuuu....",
  "..kxxKKxxk.......kuuuk..",
  ".kxxKKKKxxk.......kuuk..",
  ".kxKKKKKKxk........kk...",
  "kxxKKKKKKxxk............",
  "kxKKKKKKKKxk............",
  "kxKWWKKWWKxk............",
  "kxKKKKKKKKxk............",
  ".kxKKKKKKxk.............",
  ".kxKKKKKKxk.............",
  ".kxxKKKKxxk.............",
  "..kxKKKKxk..............",
  "..kxxKKxxk..............",
  "..kxk..kxk..............",
  "..kWk..kWk..............",
], { sym: false });

// ---- Drac (water dragon of the Rhône, blue serpentine) ----
defSprite("Drac", [
  "",
  "....bb",
  "...bBBb",
  "..bBBBBb",
  "..bBByyB",
  ".bBBBBBB",
  ".bBBBBBBb",
  "bBBWWWBBBb",
  "bBBWkkWBBb",
  ".bBBBBBBb",
  "..bBBBBb",
  "...bBBb",
  "..bBBBBb",
  ".bBBccBBb",
  "bBccBBccBb",
  "bcBBBBBBcb",
  ".bBBBBBBb",
  "..bBccBb",
  "...bBBb",
  "..bBBBBb",
  ".bBBccBBb",
  "..bBBBBb",
  "...bBBb",
  "..cc..cc",
]);

// ---- Dame Blanche (white spectral lady) ----
defSprite("Dame Blanche", [
  "",
  "....GG",
  "...GWWG",
  "..GWWWWG",
  "..GWssWG",
  "..GWssWG",
  "..GWWWWG",
  "...GWWG",
  "..GGWWGG",
  ".GWWWWWWG",
  "GWWWiiWWWG",
  "GWWiWWiWWG",
  "GWWWWWWWWG",
  ".GWWiiWWG",
  ".GWWWWWWG",
  ".GWWWWWWG",
  ".GWiWWiWG",
  ".GWWWWWWG",
  "..GWWWWG",
  "..GWWWWG",
  ".GWWiiWWG",
  ".GWWWWWWG",
  "GiiWWWWiiG",
  ".iiWWWWii",
]);

// ---- Jean de l'Ours (bear-man of the Pyrenees) ----
defSprite("Jean de l'Ours", [
  "",
  "..kk....k",
  ".kNNk..kN",
  ".kNNNkkNN",
  "..kNNNNNN",
  "..NNNNNNNn",
  "..NNkkNNNn",
  "..NNNNNNNn",
  "..NNNttNNn",
  "...NttttN",
  "...NtkktN",
  "....Ntt N",
  "..nNNNNNNn",
  ".nNNNNNNNNn",
  "nNNNttttNNN",
  "NNNttttttNN",
  "NNkttttttkN",
  "WNNttttttNN",
  "WWNNttttNNW",
  ".WNNNNNNNNW",
  "..NNNNNNNN",
  "..NNNnnNNN",
  "..kNNk.kNN",
  "..kWWk.kWW",
]);

// ---- Le Basilic (serpent king, green, crown) ----
defSprite("Le Basilic", [
  "",
  "....yky",
  "...kyKyk",
  "...keeek",
  "..keeeeek",
  "..keyyeek",
  "..keeeeek",
  ".keeeeeeek",
  ".keWWWWeek",
  ".keeeeeeek",
  "..keeeeek",
  "...keeek",
  "..keeeeek",
  ".keeqqeeek",
  "keeqEEqeeek",
  "keqEEEEqeek",
  ".keeqqeeek",
  "..keeeeek",
  "...keeek",
  "..keeeeek",
  ".keeqqeeek",
  "..keeeeek",
  "...keeek",
  "....kek",
]);

// ---- Gargantua (giant king, beard, crown) ----
defSprite("Gargantua", [
  "",
  "...ykyky",
  "..kyYkYyk",
  "..kssssss",
  ".ksssssss",
  ".ksskkssss",
  ".kssssssss",
  ".ksssnnsss",
  "..ksWWWsss",
  "..knnnnnnn",
  ".knNnNnNnn",
  ".knnnNnnnn",
  "..knnnnnn",
  ".tsssssssss",
  "tssbbbbbsss",
  "ssbbbbbbbss",
  "skbbbbbbbks",
  "Wsbbbbbbbss",
  "WWsbbbbbsss",
  ".Wssbbbsss",
  "..sssbsss",
  "..ssssssss",
  "..kssssssk",
  "..kWk.kWk",
]);

// ---- Mélusine (serpent-fairy) ----
defSprite("Mélusine", [
  "",
  "....pp",
  "...pmmp",
  "..pmssmp",
  "..pmskmp",
  "..pmsssm",
  "...mssm",
  "..PmssmP",
  ".PPssssPP",
  "PPBssssBPP",
  ".PssmmssP",
  "..ssmmss",
  "...eqqe",
  "..eqEEqe",
  ".eqEEEEqe",
  ".eEEqqEEe",
  "..eqEEqe",
  "...eEEe",
  "..eqEEqe",
  ".eqEEEEqe",
  "..eEEqe",
  "...eqEe",
  "..ee..ee",
  ".e....e",
]);

// ---- Le Diable de Laval (devil, red, horns, fire) ----
defSprite("Le Diable de Laval", [
  "",
  ".k......k",
  ".rk....kr",
  ".rrk..krr",
  "..rrkkrrr",
  "..rrrrrrr",
  "..ryYyYyr",
  "..rrrrrrr",
  ".rrkrrkrr",
  ".rrWWWWrr",
  ".rrkWkWkr",
  "..rrrrrr",
  ".frrrrrrf",
  "frrdddrrf",
  "frrdddddrf",
  "rrkdddddkr",
  "WrrdddddrW",
  "WWrrdddrrW",
  ".frrdddrf",
  "..rrrrrr",
  "..rrrrrrr",
  "..krk.krk",
  "..kKk.kKk",
  ".f.f...f",
]);

// ---- La Vouivre (winged serpent, ruby brow) ----
defSprite("La Vouivre", [
  "",
  "....ce",
  "...ceec",
  "..ceRecc",
  "..ceeyec",
  ".ceeeeec",
  ".ceWWWeec",
  "ceeeeeeec",
  "Bccceeecc",
  "BBcceeccBB",
  "cBBceecBBc",
  ".ccceeccc",
  "..cceecc",
  ".cceqqecc",
  "cceqEEqecc",
  ".cceqqecc",
  "..cceecc",
  "...ceec",
  "..cceecc",
  ".cceqqecc",
  "..cceecc",
  "...ceec",
  "..cc..cc",
  ".c....c",
]);

// ---- Gargouille (stone gargoyle, grey, wings, horns) ----
defSprite("Gargouille", [
  "",
  "..k.....k",
  "..gk...kg",
  "..ggkkggg",
  "..ggggggg",
  "..gRgggRg",
  "..ggggggg",
  ".gggWWggg",
  ".ggkWWkgg",
  "..gggggg",
  ".UggggggU",
  "UUgggggGUU",
  "UGUgggGUGU",
  "UGUgggGUGU",
  ".UggggggU",
  "..gggGgg",
  "..ggGGgg",
  ".ggGGGGgg",
  "WggGGGGggW",
  "WWggGGggWW",
  ".gggGggg",
  "..ggGgg",
  "..kggkkggk",
  "..kWk..kWk",
]);

// ---- Grand Veneur (phantom huntsman, antlers, spectral green) ----
defSprite("Grand Veneur", [
  "",
  ".k.k...k.k",
  ".qkqk.kqkq",
  "..qkqkkqkq",
  "...qqkkqq",
  "...qhhhhq",
  "...qhEEhq",
  "...qhhhhq",
  "..qqhhhhqq",
  ".qhqhhhhqhq",
  "qhhqhhhhqhhq",
  ".qhhhhhhhhq",
  "..qhhhhhhq",
  "..qhqqqqhq",
  ".qhhqqqqhhq",
  "qhhhqqqqhhhq",
  ".qhhqqqqhhq",
  "..qhhqqhhq",
  "..qhhhhhhq",
  "..qhhqqhhq",
  ".qhhhhhhhhq",
  ".qhqhhhhqhq",
  "..qhhhhhhq",
  "",
]);

// ---- Fée Morgane (enchantress, purple robe, crown) ----
defSprite("Fée Morgane", [
  "",
  "....yky",
  "...PkPkP",
  "..hhhhhh",
  ".hhssssh",
  ".hhskksh",
  ".hhsssss",
  ".hhsmmss",
  "..hhsssh",
  "..PhhhhP",
  ".PPpppPPP",
  "PPpppppPPP",
  "PpppPPpppP",
  "PppPmmPppP",
  "Ppppppppp",
  ".PppPPppP",
  ".PpppppP",
  ".PppmmppP",
  ".PppppppP",
  "PppppppppP",
  "PpPPPPPPpP",
  "Pppppppp",
  ".PPppppPP",
  "..PP..PP",
]);

// ---- Roi des Aulnes (Alder King, bark + branch crown + amber eyes) ----
defSprite("Roi des Aulnes", [
  "",
  "e.k.e.k.e",
  ".eknke.knk",
  "..knnnkkn",
  "..knNNNNk",
  "..kNyyNNk",
  "..kNNNNNk",
  ".kNNNkNNk",
  ".kNNNNNNNk",
  ".kNnNNNnNk",
  "..kNNNNNk",
  "..eknnnke",
  ".eNNNNNNNe",
  "eNNNnnnNNNe",
  "eNkNNNNNkNe",
  ".NNNnnnNNN",
  ".kNNNNNNNk",
  "eNNkNNNkNNe",
  "eeNNNNNNNee",
  ".eNNNNNNNe",
  "..NNNnNNN",
  "..kNNkkNNk",
  "..eNe..eNe",
  ".e.e...e.e",
]);

// ---- L'Ombre Souveraine (the Sovereign Shadow — final boss) ----
defSprite("L'Ombre Souveraine", [
  "",
  "...y.yky.y",
  "..yYykkyYy",
  "..xhkkkkhx",
  "..xhhhhhhx",
  ".xhhhhhhhh",
  ".xhRRhhRRx",
  ".xhRRhhRRx",
  ".xhhhhhhhh",
  "xhhhhhhhhhx",
  "xhhxhhhhxhx",
  ".xhhhhhhhx",
  "phxhhhhxhp",
  "phhxhhhhxhhp",
  "pxhhhhhhhhxp",
  ".phxhhhhxhp",
  "..pxhhhhxp",
  "..pxhRRhxp",
  "..pxhhhhxp",
  ".phxhhhhxhp",
  "phhxhhhhxhhp",
  "phxhhhhhhxhp",
  ".pxhhhhhhxp",
  "..ph....hp",
]);

// ===================== ICONS (12x12, full-width) =====================
function defIcon(name, rows, pal) {
  defSprite(name, rows, { sym: false, w: 12, pal: pal || null });
}

// Card types
defIcon("icon_attack", [
  ".....kk.....",
  "....kRRk....",
  "....kRRk....",
  "....kRRk....",
  "....kRRk....",
  "...kkRRkk...",
  "..kyyRRyyk..",
  "....nNn.....",
  "....nNn.....",
  "....kyk.....",
  "............",
  "............",
]);
defIcon("icon_skill", [
  "...kkkkkk...",
  "..kEEEEEEk..",
  "..kEqqqqEk..",
  "..kEqEEqEk..",
  "..kEqEEqEk..",
  "..kEqqqqEk..",
  "...kEqqEk...",
  "...kEEEEk...",
  "....kEEk....",
  ".....kk.....",
  "............",
  "............",
]);
defIcon("icon_power", [
  ".....k......",
  "....kyk.....",
  "....kyk.....",
  "...kyYyk....",
  "...kyYyk....",
  "..kyYYYyk...",
  "..oyYYYyo...",
  "..oyYYYyo...",
  "...oyyyo....",
  "....ooo.....",
  "............",
  "............",
]);

// Keyword chips
defIcon("icon_block", [
  "...kkkkkk...",
  "..kiiiiiik..",
  "..kicccici..",
  "..kiccccii..",
  "..kicccici..",
  "..kiccccii..",
  "...kicciik..",
  "...kiccik...",
  "....kiik....",
  ".....kk.....",
  "............",
  "............",
]);
defIcon("icon_strength", [
  ".....kk.....",
  "....kRRk....",
  "...kRRRRk...",
  "..kRRRRRRk..",
  ".kRRRRRRRRk.",
  "kRRRRRRRRRRk",
  "....kRRk....",
  "....kRRk....",
  "....kRRk....",
  "....kkkk....",
  "............",
  "............",
]);
defIcon("icon_vuln", [
  "............",
  "..kk....kk..",
  ".koRk..koRk.",
  ".koooooooork",
  "..koooooork.",
  "...kooork...",
  "....koRk....",
  ".....kk.....",
  "............",
  "............",
  "............",
  "............",
]);
defIcon("icon_weak", [
  "............",
  "..kpppppk...",
  ".kpPPPPPpk..",
  ".kpPpppPpk..",
  ".kpPpppPpk..",
  "..kpppppk...",
  "...kpppk....",
  "....kpk.....",
  ".....k......",
  "............",
  "............",
  "............",
]);
defIcon("icon_energy", [
  ".....k......",
  "....kbk.....",
  "...kbBbk....",
  "..kbBBBbk...",
  ".kbBYYBbk...",
  ".kbBYBBbk...",
  ".kbBBYBbk...",
  ".kbBYBBbk...",
  "..kbBBbk....",
  "...kbbk.....",
  "....kk......",
  "............",
]);
defIcon("icon_armor", [
  "............",
  "..kuuuuuuk..",
  ".kuUUuuUUuk.",
  ".kuUuuuuUuk.",
  ".kuuuuuuuuk.",
  ".kuUuuuuUuk.",
  ".kuUUuuUUuk.",
  ".kuuuuuuuuk.",
  "..kuuuuuuk..",
  "...kkkkkk...",
  "............",
  "............",
]);
defIcon("icon_poison", [
  ".....k......",
  "....kek.....",
  "...keEek....",
  "..keEEEek...",
  ".keEqqEEek..",
  ".keEqkqEek..",
  ".keEEEEEek..",
  ".keEqEqEek..",
  "..keEEEek...",
  "...keeek....",
  "....kk......",
  "............",
]);

// Intents (used in the intent bubble)
defIcon("intent_attack", [
  ".........kk.",
  "........kRRk",
  ".......kRRk.",
  "......kRRk..",
  ".....kRRk...",
  "....kRRk....",
  "...kRRk.....",
  "..nkRk......",
  ".nNRk.......",
  "knnk........",
  ".yk.........",
  "............",
]);
defIcon("intent_multi", [
  "......k...k.",
  ".....kRk.kRk",
  "....kRkkRRk.",
  "...kRkkRRk..",
  "..kRkkRRk...",
  ".kRkkRRk....",
  "kRkkRRk.....",
  "nkkRk.......",
  "nNRkk.......",
  "nnk.........",
  "............",
  "............",
]);
defIcon("intent_block", [
  "...kkkkkk...",
  "..kiiiiiik..",
  "..kiccccii..",
  "..kiccccii..",
  "..kiccccii..",
  "..kiccccii..",
  "...kicciik..",
  "...kiccik...",
  "....kiik....",
  ".....kk.....",
  "............",
  "............",
]);
defIcon("intent_buff", [
  ".....kk.....",
  "....kEEk....",
  "...kEEEEk...",
  "..kEEEEEEk..",
  ".kEEEEEEEEk.",
  "kEEEEEEEEEEk",
  "....kEEk....",
  "....kEEk....",
  "....kEEk....",
  "....kkkk....",
  "............",
  "............",
]);
defIcon("intent_debuff", [
  "....kkkk....",
  "....kppk....",
  "....kppk....",
  "....kppk....",
  "kpppppppppk.",
  ".kpppppppk..",
  "..kpppppk...",
  "...kpppk....",
  "....kpk.....",
  ".....k......",
  "............",
  "............",
]);
defIcon("intent_unknown", [
  "...kkkkk....",
  "..kPPPPPk...",
  ".kPPkkkPPk..",
  ".kPk..kPPk..",
  "......kPPk..",
  ".....kPPk...",
  "....kPPk....",
  "....kPk.....",
  "....kPk.....",
  "............",
  "....kPk.....",
  "....kkk.....",
]);
